M48
; DRILL file {KiCad (6.0.1)} date Thu Apr 20 11:25:53 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-20T11:25:53+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.500
%
G90
G05
T1
X43.908Y-92.51
T2
X76.75Y-60.5
X76.75Y-126.6
X127.35Y-60.5
X127.35Y-126.6
X174.65Y-60.5
X174.65Y-126.6
X225.25Y-60.5
X225.25Y-126.6
T3
X100.0Y-52.5
X187.0Y-134.5
T0
M30
